// <auto-generated />
using System;
using LuckyDraw.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LuckyDraw.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220825034311_allTable01")]
    partial class allTable01
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LuckyDraw.Models.BarcodeModel", b =>
                {
                    b.Property<int>("BarcodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BarcodeCode")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("BarcodeCount")
                        .HasColumnType("int");

                    b.Property<int>("BarcodeRedemptionLimit")
                        .HasColumnType("int");

                    b.Property<bool>("BarcodeScanned")
                        .HasColumnType("bit");

                    b.Property<DateTime>("BarcodeScannedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("BarcodeSpinDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("BarcodeUnilimited")
                        .HasColumnType("bit");

                    b.Property<bool>("BarcodeUseSpin")
                        .HasColumnType("bit");

                    b.Property<string>("QRCode")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("BarcodeId");

                    b.ToTable("Barcode");
                });

            modelBuilder.Entity("LuckyDraw.Models.CampaignModel", b =>
                {
                    b.Property<int>("CampaignId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("CampaignApplyAll")
                        .HasColumnType("bit");

                    b.Property<bool>("CampaignAutoUpdate")
                        .HasColumnType("bit");

                    b.Property<int>("CampaignBarcode")
                        .HasColumnType("int");

                    b.Property<string>("CampaignCharset")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("CampaignCount")
                        .HasColumnType("int");

                    b.Property<string>("CampaignDescription")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CampaignEndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CampaignGift")
                        .HasColumnType("int");

                    b.Property<int>("CampaignLength")
                        .HasColumnType("int");

                    b.Property<string>("CampaignName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CampaignNote")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("CampaignOnly")
                        .HasColumnType("bit");

                    b.Property<string>("CampaignPostfix")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CampaignPrefix")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("CampaignProgramName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CampaignStarDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("CampaignUnlimited")
                        .HasColumnType("bit");

                    b.Property<int>("CampaignUsageLimit")
                        .HasColumnType("int");

                    b.HasKey("CampaignId");

                    b.HasIndex("CampaignBarcode");

                    b.HasIndex("CampaignGift")
                        .IsUnique();

                    b.ToTable("Campaigns");
                });

            modelBuilder.Entity("LuckyDraw.Models.CustomerModel", b =>
                {
                    b.Property<int>("CustomerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CustomerAddress")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CustomerBirtday")
                        .HasColumnType("datetime2");

                    b.Property<bool>("CustomerBlock")
                        .HasColumnType("bit");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CustomerPassword")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("CustomerPosition")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("CustomerTypeBusinees")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("CustomerID");

                    b.HasIndex("Role");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("LuckyDraw.Models.GiftModel", b =>
                {
                    b.Property<int>("GiftId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("GiftActive")
                        .HasColumnType("bit");

                    b.Property<string>("GiftCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("GiftCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("GiftCreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("GiftCustommer")
                        .HasColumnType("int");

                    b.Property<string>("GiftDescription")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("GiftProductName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("GiftUsed")
                        .HasColumnType("int");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.HasKey("GiftId");

                    b.HasIndex("GiftCustommer");

                    b.ToTable("Gifts");
                });

            modelBuilder.Entity("LuckyDraw.Models.RoleModel", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("RoleName")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("LuckyDraw.Models.RuleModel", b =>
                {
                    b.Property<int>("RuleId")
                        .HasColumnType("int");

                    b.Property<int>("RuleAmount")
                        .HasColumnType("int");

                    b.Property<DateTime>("RuleEndDay")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("RuleEndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("RuleMonthly")
                        .HasColumnType("datetime2");

                    b.Property<string>("RuleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("RuleProbability")
                        .HasColumnType("int");

                    b.Property<string>("RuleSelectGift")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("RuleStartDay")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("RuleStartTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("RuleWeekly")
                        .HasColumnType("datetime2");

                    b.Property<bool>("RullAllDay")
                        .HasColumnType("bit");

                    b.HasKey("RuleId");

                    b.ToTable("Rules");
                });

            modelBuilder.Entity("LuckyDraw.Models.WinnerModel", b =>
                {
                    b.Property<int>("WinnerCustommerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("WinnerDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("WinnerGift")
                        .HasColumnType("int");

                    b.Property<bool>("WinnerStatus")
                        .HasColumnType("bit");

                    b.HasKey("WinnerCustommerId");

                    b.HasIndex("WinnerGift");

                    b.ToTable("Winner");
                });

            modelBuilder.Entity("LuckyDraw.Models.CampaignModel", b =>
                {
                    b.HasOne("LuckyDraw.Models.BarcodeModel", "barcodeModel")
                        .WithMany()
                        .HasForeignKey("CampaignBarcode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LuckyDraw.Models.GiftModel", "giftModel")
                        .WithOne("campaignModel")
                        .HasForeignKey("LuckyDraw.Models.CampaignModel", "CampaignGift")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("barcodeModel");

                    b.Navigation("giftModel");
                });

            modelBuilder.Entity("LuckyDraw.Models.CustomerModel", b =>
                {
                    b.HasOne("LuckyDraw.Models.RoleModel", "roleModel")
                        .WithMany()
                        .HasForeignKey("Role")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("roleModel");
                });

            modelBuilder.Entity("LuckyDraw.Models.GiftModel", b =>
                {
                    b.HasOne("LuckyDraw.Models.CustomerModel", "CustomerModel")
                        .WithMany()
                        .HasForeignKey("GiftCustommer")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomerModel");
                });

            modelBuilder.Entity("LuckyDraw.Models.RuleModel", b =>
                {
                    b.HasOne("LuckyDraw.Models.GiftModel", "giftModel")
                        .WithOne("ruleModel")
                        .HasForeignKey("LuckyDraw.Models.RuleModel", "RuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("giftModel");
                });

            modelBuilder.Entity("LuckyDraw.Models.WinnerModel", b =>
                {
                    b.HasOne("LuckyDraw.Models.GiftModel", "gift")
                        .WithMany()
                        .HasForeignKey("WinnerGift")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("gift");
                });

            modelBuilder.Entity("LuckyDraw.Models.GiftModel", b =>
                {
                    b.Navigation("campaignModel");

                    b.Navigation("ruleModel");
                });
#pragma warning restore 612, 618
        }
    }
}
